version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    ports:
      - "8082:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

#  payment:
#    build:
#      context: .
#      dockerfile: payment/Dockerfile
#    ports:
#      - "8081:8081"
#    environment:
#      - SERVER_PORT=8081
#      - SPRING_R2DBC_URL=r2dbc:h2:mem:///payment;DB_CLOSE_DELAY=-1
#      - JWT_ISSUER_URI=http://keycloak:8080/realms/my-market-app
#    depends_on:
#      keycloak:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#
#  shop:
#    build:
#      context: .
#      dockerfile: shop/Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - SERVER_PORT=8080
#      - SPRING_DATA_REDIS_HOST=redis
#      - PAYMENT_SERVICE_URL=http://payment:8081/payments/api
#    depends_on:
#      redis:
#        condition: service_healthy
#      payment:
#        condition: service_started
