server.port=8080

spring.application.name=shop
spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:h2:mem:///shop;DB_CLOSE_DELAY=-1}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:sa}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:}

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
spring.sql.init.mode=always

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.connect-timeout=2s
spring.data.redis.timeout=1s
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8081/payments/api}

logging.level.ru.yandex.practicum=DEBUG
app.cookie.max-age=7d