DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS items;

CREATE TABLE
    items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)   NOT NULL,
    description VARCHAR(1000)  NOT NULL,
    img_path    VARCHAR(255)   NOT NULL,
    price       NUMERIC(15, 2) NOT NULL,
    count       INTEGER        NOT NULL DEFAULT 0
);


CREATE TABLE carts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID    NOT NULL,
    item_id    BIGINT  NOT NULL,
    count      INTEGER NOT NULL,
    version    BIGINT  NOT NULL DEFAULT 0,

    CONSTRAINT fk_carts_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT uk_carts_session_item UNIQUE (session_id, item_id),
    CONSTRAINT chk_carts_count_positive CHECK (COUNT > 0)
);

CREATE INDEX idx_carts_session ON carts (session_id);

CREATE TABLE orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID           NOT NULL,
    total      NUMERIC(15, 2) NOT NULL
);

CREATE INDEX idx_orders_session ON orders (session_id);

CREATE TABLE order_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT  NOT NULL,
    item_id  BIGINT  NOT NULL,
    COUNT    INTEGER NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT uk_order_items UNIQUE (order_id, item_id)
);

CREATE INDEX idx_order_items_order ON order_items (order_id);