spring.application.name=my-market-app

spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/market}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:pgsql}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:pgsql}

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
spring.sql.init.mode=always

logging.level.ru.yandex.practicum.mymarket=DEBUG