name: Java CI – Unit & Integration Tests (Gradle)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read

    steps:
      - name: Force Node.js 24
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradlew check

      - name: Publish Test Results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Gradle Tests
          path: "**/build/test-results/**/*.xml"
          reporter: java-junit